name: deploy
on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/main.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root//mern-todo-app
            git pull
            docker-compose up -d --build --remove-orphans frontend-react
            docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi

#================================
#        Ghi chú thêm
#================================
# ✅ chỉ chạy khi FE thay đổi hoặc file workflow này thay đổi
# paths:
#   - "frontend/**"
#   - ".github/workflows/main.yml"

# ✅ Stop
# docker-compose stop frontend-react

# ✅ Start lại (không rebuild)
# docker-compose start frontend-react

# ✅ Stop + xóa container (chỉ service đó)
# docker-compose rm -sf frontend-react

# ✅ Rebuild + start lại
#docker-compose up -d --build frontend-react
